apiVersion: v1
kind: Service
metadata:
  name: litecoin
  labels:
    app: litecoin
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: litecoin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  selector:
    matchLabels:
      app: litecoin 
  serviceName: "litecoin"
  replicas: 2 
  template:
    metadata:
      labels:
        app: litecoin 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: litecoin
        image: alizandieh2019/litecoin:0.18.1
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: litecoin-vol
          mountPath: /home/litecoin/.litecoin
  volumeClaimTemplates:
  - metadata:
      name: litecoin-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi
# didn't mention StorageClass here to use the default StorageClass in the cluster